#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Generate the RCON password into state/passwords.env (mode 0600): secrets must
# not be stored in state/environment, which NS8 mirrors to Redis in plain text.

import secrets

import modsecrets

modsecrets.ensure({"RCON_PASSWORD": secrets.token_urlsafe(24)})
